### ISSUE TITLE
Framework?

### ISSUE THREAD

**Issue by clanshood** [clanshood/smart-paper-project-prepare#1]
@moszes sidone pak nganggo frameworke opo jaremu?

a. meanio
b. meteor
c. angular-fullstack

asli aku bingung, durung tau nganggo puU, tapi setil-setil.

**Comment by mahatmamahardhikach** [comment]
manut mastere ae ra ... wkkwkw

**Comment by clanshood** [comment]
asem, ojo kokui ra kk,,
aku weruh meteor mangkleh kok tertarik nganggo kui kk,,
pimen jaremu?

**Comment by mahatmamahardhikach** [comment]
ya wes meteor ae ... mengko bar jum'atan tak boco2 ... :D

**Comment by clanshood** [comment]
sip wes, fixed ya..

**Comment by mahatmamahardhikach** [comment]
wokeeee

**Comment by clanshood** [comment]
sek sek kk,, ketoke aku salah paham ki,,
durung kelar moco wes buru2 pingin nganggo..

**Comment by mahatmamahardhikach** [comment]
wkkwkw .... gampang ganti maneh po o

**Comment by clanshood** [comment]
meteor eliminasi, aku rekomendasi angular-fullstack. pimen kk?
- [ ] meanio
- [ ] ~~meteor~~
- [x] angular-fullstack

**Comment by clanshood** [comment]
fixed!!
- [x] angular-fullstack
